name: 001_xrestormer_sr
model_type: XRestormerModel
scale: 4
num_gpu: 0
manual_seed: 123
padding_size: 16

# dataset and data loader settings
datasets:
  test_1:
    name: test
    type: SingleImageDataset
    dataroot_lq: data/raw/Test
    sigma_test: 50
    in_ch: 3  ## RGB image
    io_backend:
      type: disk

# network structures
network_g:
  type: XRestormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [2,4,4,4]
  num_refinement_blocks: 4
  channel_heads: [1,2,4,8]
  spatial_heads: [1,2,4,8]
  overlap_ratio: [0.5,0.5,0.5,0.5]
  window_size: 8
  spatial_dim_head: 16
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False
  scale: 4

# path
path:
  pretrain_network_g: modules/X-Restormer/experiments/SR/sr_300k.pth
  strict_load_g: true
  resume_state: ~
  results: data/processed/
# validation settings
val:
  save_img: true
  suffix: ~